version: '1.0'
name: my_project
profile: spark-local
target-path: /.output/dbt
data-paths:
  - data/seeds
clean-targets:
  - .cache/.dbt
source-paths:
  - data/transforms
models:
  my_project:
    dummy_schema_sample:
      enabled: true
      materialized: table
    linked_in_sample:
      enabled: false
      materialized: table
test-paths:
  - testing/queries
analysis-paths:
  - reporting/queries
  - tests/queries
# macro-paths:
# - scripts/dbt-macros
