# shortname: meltano
# profiles-dir: profile
analysis-paths:
  - reporting/queries
  - tests/queries
clean-targets:
- .cache/.dbt
data-paths:
- data/seeds
# macro-paths:
# - scripts/dbt-macros
models:
  my_project:
    dummy_schema_sample:
      enabled: true
      materialized: table
    linked_in_sample:
      enabled: false
      materialized: table
name: my_project
profile: spark-local
source-paths:
- data/transforms
target-path: /.output/dbt
test-paths:
- testing/queries
version: '1.0'
