version: '1.0'

name: my_project
profile: spark-local

# 1. Seed Data (raw CSV files):
data-paths:
  - data/transforms/_raw_
seeds:
  my_project:
    list_integers:
      enabled: true
      column_types:
        integer: bigint

# 2. Model Files (SQL transforms and YAML configs):
source-paths:
  - data/transforms
models:
  my_project:
    dummy_schema_sample:
      enabled: false
      materialized: table
    linked_in_v1:
      enabled: false
      materialized: table
    linked_in_v2:
      enabled: false
      materialized: table

# 3. SQL Tests (queries that expect zero results)
test-paths:
  - data/tests/sql

# 4. Downstream Analyses (queries should compile but won't be executed)
analysis-paths:
  - data/analysis/sql
  - data/tests/sql

# 5. Output Directory (for compilation and build results)
target-path: .output/dbt
clean-targets:
  - .output/dbt
