version: '3.1'
volumes:
  warehouse:
services:
  dataops_dev:
    container_name: dataops_dev
    build:
      context: ..
      args: []
    working_dir: /projects/my-project
    command: s-spark start_server --with_jupyter
    environment:
      - PROJECT_NAME=dataops-project
      - PYTHONUNBUFFERED=1
      - SPARK_WAREHOUSE_DIR=/spark_warehouse
      - SPARK_UDF_MODULE=
    volumes:
      # - /c/:/c/
      - ..:/projects/.source
      # - ~/.aws/credentials:/home/.aws/credentials
      # - ./.vscode-server/:/root/.vscode-server
      # - ./.vscode-server-insiders/:/root/.vscode-server-insiders
      - ../data:/projects/my-project/data
      - ../tools:/projects/my-project/tools
      - ../infra:/projects/my-project/infra
      - ../logs:/projects/my-project/logs
      - ../.output:/projects/my-project/.output
      - ../.secrets:/projects/my-project/.secrets
      - warehouse:/spark_warehouse
      # - ../.output/spark:/spark_warehouse  # MySQL fails if dir mapped directly
      # - ..:/projects/my-project  R Redundant
    ports:
      - "4040:4040"    # App Web UI
      - "7077:7077"    # Standalone master driver
      - "8080:8080"    # Standalone-mode master Web UI
      - "8081:8081"    # Standalone-mode worker Web UI
      - "10000:10000"  # Thrift JDBC port for SQL queries
      - "18080:18080"  # History Server Web UI
  # spark:
  #   container_name: spark
  #   image: slalomggp/dataops:latest-dev
  #   command: "spark start_server"
  #   volumes:
  #     - ~/.aws/credentials:/home/.aws/credentials
  #   environment:
  #     # If reading from S3, this must match the S3 bucket's region:
  #     - AWS_DEFAULT_REGION=us-east-2
  #   ports:
  #     - "4040:4040"    # App Web UI
  #     - "7077:7077"    # Standalone master driver
  #     - "8080:8080"    # Standalone-mode master Web UI
  #     - "8081:8081"    # Standalone-mode worker Web UI
  #     - "10000:10000"  # Thrift JDBC port for SQL queries
  #     - "18080:18080"  # History Server Web UI
  # postgres:
  #   container_name: postgres
  #   image: postgres:11
  #   command: ["-c", "listen_addresses=*"]
  #   environment:
  #     POSTGRES_DB: warehouse
  #     POSTGRES_USER: warehouse
  #     POSTGRES_PASSWORD: warehouse
  #   ports:
  #     - '5502:5432'
