version: '3.1'
services:
  meltano_dev:
    build: 
      context: ..
      args: []
    container_name: meltano
    user: root
    working_dir: /projects/meltano-project
    ports:
     - "5000:5000"
     - "5010:5010"
    volumes:
     - /c/:/c/
     - ../meltano-project:/projects/meltano-project
     - ..:/projects/.source
     - ./.vscode-server/:/root/.vscode-server
     - ./.vscode-server-insiders/:/root/.vscode-server-insiders
    #  - ~/.aws/credentials:/home/jovyan/.aws/credentials
    environment:
      - MELTANO_ROOT=/projects/meltano-project
      - PROJECT_NAME=meltano-project
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  meltano_db:
    image: postgres:11
    container_name: warehouse
    # command: ["-c", "\"listen_addresses='*'\""]
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_USER: warehouse
    ports:
    - '5502:5432'
  spark_db:
    image: slalomggp/dataops:latest-dev
    container_name: spark
    command: "spark start_server"
    volumes:
    - ~/.aws/credentials:/home/.aws/credentials
    environment:
    # If reading from S3, this must match the S3 bucket's region:
    - AWS_DEFAULT_REGION=us-east-2
    ports:
    - "4040:4040"    # App Web UI
    - "7077:7077"    # Standalone master driver
    - "8080:8080"    # Standalone-mode master Web UI
    - "8081:8081"    # Standalone-mode worker Web UI
    - "10000:10000"  # Thrift JDBC port for SQL queries
    - "18080:18080"  # History Server Web UI
