analysis-paths:
- analysis
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_modules
data-paths:
- data
macro-paths:
- macros
models:
  # my_meltano_project: null
  tap_salesforce:
    vars:
      schema: '{{ env_var(''MELTANO_LOAD_SCHEMA'') }}'
name: my_meltano_project
profile: meltano
source-paths:
- models
target-path: ../.meltano/transformers/dbt/target
test-paths:
- tests
version: '1.0'
