name: Automated Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Build Docker image
        run: ./gradelw dockerCompose
      - name: Compile DBT project
        run: ./gradelw dbtCompile
      - name: Run DBT project
        run: ./gradelw dbtRun
      - name: Run DBT project tests
        run: ./gradelw dbtTest
      - name: Build DBT Project Docs
        run: ./gradelw dbtDocs
      - name: Check spark outputs
        run: >
          docker run --rm
          -v warehouse:/spark_warehouse
          -w /spark_warehouse/data
          ubuntu:18.04
          ls -lah /spark_warehouse/data
