name: Automated Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
      - name: Fix permissions
        run: |
          chmod 777 ./gradlew
          pwd && ls -la
      - name: Install prereqs
        run: |
          apt-get install -y python3-setuptools
          pip3 install docker-compose
      - name: Build Docker image
        # run: docker-compose        --project-name dataops-project-template_devcontainer        -f .devcontainer/docker-compose.dev.yml        build
        run: ./gradlew dockerCompose --stacktrace --info
      - name: Compile DBT project
        run: ./gradlew dbtCompile
      - name: Load seed files
        run: ./gradlew dbtSeed
      - name: Run SQL transforms
        run: ./gradlew dbtRun
      - name: Run tests
        run: ./gradlew dbtTest
      - name: Generate data dictionary docs
        run: ./gradlew dbtDocs
      - name: Check spark outputs
        run: >
          docker run --rm
          -v warehouse:/spark_warehouse
          -w /spark_warehouse/data
          ubuntu:18.04
          ls -lah /spark_warehouse/data
